server:
  port: 8100
spring:
  config:
    import: optional:configserver:http://localhost:8104
  application:
    name: STORE-GATEWAY
  main:
    allow-bean-definition-overriding: true
    security:
      oauth2:
        client:
          registration:
            keycloak:
              client-id: ${KEYCLOAK_CLIENT_ID}
              client-secret: ${KEYCLOAK_CLIENT_SECRET}
              scope: openid
              authorization-grant-type: client_credentials
              token-uri: ${KEYCLOAK_TOKEN_ENDPOINT}
          provider:
            keycloak:
              issuer-uri: ${KEYCLOAK_ISSUER_ENDPOINT}

  cloud:
    gateway:
      routes:
        - id: store-authorization
          uri: lb://STORE-AUTHORIZATION
          predicates:
            - Path=/store-authorization/**

        - id: store-product-catalog
          uri: lb://STORE-PRODUCT-CATALOG
          predicates:
            - Path=/store-product-catalog/**

        - id: store-order
          uri: lb://STORE-ORDER
          predicates:
            - Path=/store-order/**


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL}