create table public.t_order (
    order_id bigint generated by default as identity,
    user_id bigint not null,
    product_id bigint not null,
    quantity integer not null,
    primary key (order_id)
);