create table public.order_created_event_unique (
    id bigint generated by default as identity,
    message_id varchar(255) not null unique,
    order_id varchar(255) not null,
    primary key (id)
);